☁️ chore(automation): Automated update

diff --git a/.config/taskfiles/ansible/Taskfile-test.yml b/.config/taskfiles/ansible/Taskfile-test.yml
--- a/.config/taskfiles/ansible/Taskfile-test.yml
+++ b/.config/taskfiles/ansible/Taskfile-test.yml
@@ -11,7 +11,11 @@ vars:
       if [ -n "$CI" ]; then
         echo ''
       else
-        echo 'unbuffer {{.PYTHON_HANDLE}}'
+        if type unbuffer &> /dev/null; then
+          echo 'unbuffer {{.PYTHON_HANDLE}}'
+        else
+          echo '{{.PYTHON_HANDLE}}'
+        fi
       fi
 
 tasks:
@@ -756,6 +760,8 @@ tasks:
         msg: The `molecule/default/molecule.yml` file must be present and in the proper format
 
   post:molecule:log:
+    deps:
+      - :ci:commit:config
     cmds:
       - task: ansifilter
         vars:
@@ -763,8 +769,9 @@ tasks:
       - task: post:molecule:log:commit:ci
       - cmd: |
           git pull --ff-only origin master
+          task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
           git add '{{.RESULTS_FILE}}'
-          HUSKY=0 git commit -m "📝 docs(test results): new molecule test results added [ci skip]" -n
+          HUSKY=0 git commit -o ci.skip -m "📝 docs(molecule): New Molecule test results added." -n
           git push origin master
         ignore_error: true
     status:
diff --git a/.config/taskfiles/fix/Taskfile.yml b/.config/taskfiles/fix/Taskfile.yml
--- a/.config/taskfiles/fix/Taskfile.yml
+++ b/.config/taskfiles/fix/Taskfile.yml
@@ -23,7 +23,7 @@ tasks:
     deps:
       - :install:modules:local
       - :install:npm:eslint
-      - :install:software:expect
+      - :install:software:unbuffer
     desc: Fix ESLint errors automatically
     summary: |
       # Fix Errors with ESLint Automatically
@@ -37,28 +37,29 @@ tasks:
 
       **Example fixing all files in a project:**
       `task fix:js`
+    vars:
+      ESLINT_LOG:
+        sh: mktemp
     log:
       error: ESLint found some issues that need to be fixed manually
       start: Auto-fixing with ESLint
       success: ESLint fixing appears to have corrected all the issues {{if .CLI_ARGS}}in `{{.CLI_ARGS}}`{{else}}in the project{{end}}
     cmds:
       - 'unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache
-        --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee eslint.log'
+        --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee {{.ESLINT_LOG}}'
       - |
         if [ '{{.ESLINT_FIX_RECURSIVE}}' == 'true' ]; then
           COUNT=0
           while [ $COUNT -le 5 ]; do
             COUNT=$((COUNT + 1))
-            if grep 'potentially fixable with the `--fix` option' < eslint.log > /dev/null; then
+            if grep 'potentially fixable with the `--fix` option' < {{.ESLINT_LOG}} > /dev/null; then
               COUNT="$COUNT"
               unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache \
-              --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee eslint.log
-            else
-              echo '' > eslint.log
+              --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee {{.ESLINT_LOG}}
             fi
           done
         fi
-      - rm eslint.log
+      - rm {{.ESLINT_LOG}}
 
   eslint:staged:
     deps:
@@ -77,40 +78,25 @@ tasks:
         --cache-location .cache/eslintcache --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   go:
+    deps:
+      - :install:software:go
+      - :install:software:golangci-lint
     desc: Fix Go with all available Go fixers
     summary: |
       # Auto-Fix Go Files
 
-      This task will attempt to auto-fix Go files with the following auto-fixers:
-
-      * [go]()
-
-      If you would like to skip auto-fixing on the whole project and instead auto-fix an
-      individual file, then you can do so by passing the file path as a CLI
-      parameter like so:
+      This task will attempt to auto-fix Go files with
+      [golangci-lint](https://golangci-lint.run/) which runs multiple linters all
+      defined in `.config/golangci-lint`.
 
       **Example auto-fixing an individual file:**
       `task fix:go -- path/filename.go`
+    log:
+      error: Encountered error while autofixing Go files
+      start: Auto-fixing Go files..
+      success: Successfully auto-fixed Go files
     cmds:
-      - task: go:fmt
-
-  go:fmt:
-    deps:
-      - :install:software:go
-    summary: |
-      # Auto-Fix Go Files with `gofmt`
-
-      Running this task will auto-format the Go code in the project with `gofmt`.
-      In addition to writing the files (via the `-w` flag), it also attempts to
-      simplify the files (via the `-s` flag).
-
-      By default, this task will format the entire project. However, you can target
-      specific files by passing the path of the `.go` file as a CLI argument.
-
-      **Example formatting specific file:**
-      `task fix:go:fmt -- path/to/file.go`
-    cmds:
-      - gofmt -s -w {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - golangci-lint run -c .config/golangci.yml --fix{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
 
   js:
     cmds:
@@ -174,7 +160,7 @@ tasks:
 
   misc:
     deps:
-      - :install:python:requirements
+      - :install:pipx:pre-commit-hooks
     summary: |
       # Miscellaneous fixes
 
@@ -196,8 +182,8 @@ tasks:
     cmds:
       - |
         function misc() {
-          {{.PYTHON_HANDLE}}fix-byte-order-marker "$1"
-          {{.PYTHON_HANDLE}}mixed-line-ending --fix=lf "$1"
+          fix-byte-order-marker "$1"
+          mixed-line-ending --fix=lf "$1"
         }
         {{if .CLI_ARGS}}
           misc '{{.CLI_ARGS}}'
@@ -289,16 +275,17 @@ tasks:
     log:
       start: Running Prettier on {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}}
     cmds:
-      - |
-        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
-        if [ -n "$EXIT_CODE" ]; then
-          .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
-          prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
-        fi
+      - cmd: |
+          {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+          if [ -n "$EXIT_CODE" ]; then
+            .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+            prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+          fi
+        ignore_error: true
 
   python:
     deps:
-      - :install:python:requirements
+      - :install:pipx:black
     desc: Automatically format Python files using Black
     hide: '{{ne .REPOSITORY_TYPE "python"}}'
     summary: |
@@ -322,10 +309,10 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
-          {{.PYTHON_HANDLE}}black {{.CLI_ARGS}}
+          black {{.CLI_ARGS}}
         {{else}}
           while read PATHH; do
-            {{.PYTHON_HANDLE}}black "$PATHH"
+            black "$PATHH"
           done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.py' \))
         {{end}}
 
@@ -392,7 +379,7 @@ tasks:
 
   toml:
     deps:
-      - :install:python:requirements
+      - :install:pipx:toml-sort
     desc: Format `.toml` files by alphabetizing and flattening
     summary: |
       # Automatically format `.toml` files
@@ -412,10 +399,12 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
-          {{.PYTHON_HANDLE}}toml-sort -i --all {{.CLI_ARGS}}
+        if [ -f '{{.CLI_ARGS}}' ]; then
+          toml-sort -i --all {{.CLI_ARGS}}
+        fi
         {{else}}
           while read PATHH; do
-            {{.PYTHON_HANDLE}}toml-sort -i --all "$PATHH"
+            toml-sort -i --all "$PATHH"
           done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.toml' \))
         {{end}}
 
diff --git a/.config/taskfiles/git/Taskfile-gitlab.yml b/.config/taskfiles/git/Taskfile-gitlab.yml
--- a/.config/taskfiles/git/Taskfile-gitlab.yml
+++ b/.config/taskfiles/git/Taskfile-gitlab.yml
@@ -15,7 +15,7 @@ tasks:
         sh: glab api projects/:fullpath | jq '.id'
       REQUEST_DATA: '{ "name":"PROJECT_CI_ACCESS_TOKEN", "scopes":["write_repository", "read_repository"] }'
       TOKEN_STATUS:
-        sh: glab api projects/:fullpath/access_tokens | jq -r '.[] | select(.name=="PROJECT_CI_ACCESS_TOKENX") | .id'
+        sh: type glab > /dev/null && glab api projects/:fullpath/access_tokens | jq -r '.[] | select(.name=="PROJECT_CI_ACCESS_TOKENX") | .id' || true
     run: once
     log:
       error: Failed to configure project-specific access token
@@ -27,7 +27,7 @@ tasks:
         'Content-Type:application/json' --data '{{.REQUEST_DATA}}' \
         'https://gitlab.com/api/v4/projects/{{.REPO_ID}}/access_tokens' > /dev/null
     status:
-      - '[ -n "{{.TOKEN_STATUS}}" ]'
+      - '[ -n "{{.TOKEN_STATUS}}" ] || ! glab api projects/:fullpath/access_tokens'
 
   branches:
     deps:
@@ -113,9 +113,10 @@ tasks:
           NO_PROMPT=1 glab repo create '{{.GITLAB_PATH}}' --group '{{.GITLAB_GROUP}}' \
           --description '{{.EMOJI_START}}{{.DESCRIPTION}}{{.EMOJI_END}}' --name '{{.NAME}}' \
           {{.PROJECT_TYPE}} --tag "$(jq -r '.keywords | tostring' package.json | sed 's/\[//' | sed 's/\]//')"
+          task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
           git add --all
           HUSKY=0 git commit --quiet -m "🎂 Birth" -n || true
-          git push --quiet -u --no-progress gitlab master
+          git push gitlab master
         ignore_error: true
     status:
       - '[ -z "$GITLAB_TOKEN" ] || (test -d .git && glab repo view "{{.GITLAB_PATH}}" > /dev/null)'
@@ -329,7 +330,38 @@ tasks:
       - sh: '[ ! -z "$GITLAB_TOKEN" ]'
         msg: The `GITLAB_TOKEN` environment variable must be set to run this task
 
+  protected:off:
+    deps:
+      - :install:software:glab
+    vars:
+      BRANCH: '{{if .BRANCH}}{{.BRANCH}}{{else}}{{.CLI_ARGS}}{{end}}'
+    todo: figure out how to do it without deleteing the protection first
+    cmds:
+      - glab api projects/:fullpath/protected_branches/{{.BRANCH}} -X DELETE
+      - glab api projects/:fullpath/protected_branches -X POST -f name={{.BRANCH}} -f allow_force_push=true > /dev/null
+    status:
+      - '[ -z "$GITLAB_TOKEN" ]'
+
+  protected:on:
+    deps:
+      - :install:software:glab
+    vars:
+      BRANCH: '{{if .BRANCH}}{{.BRANCH}}{{else}}{{.CLI_ARGS}}{{end}}'
+    todo: figure out how to do it without deleteing the protection first
+    cmds:
+      - glab api projects/:fullpath/protected_branches/{{.BRANCH}} -X DELETE
+      - glab api projects/:fullpath/protected_branches -X POST -f name={{.BRANCH}} -f allow_force_push=false > /dev/null
+    status:
+      - '[ -z "$GITLAB_TOKEN" ]'
+
   update:
+    run: once
+    cmds:
+      - task: update:deps
+    status:
+      - '[ -z "$GITLAB_TOKEN" ] || ! type glab &> /dev/null'
+
+  update:deps:
     deps:
       - access-token
       - branches
diff --git a/.config/taskfiles/git/Taskfile.yml b/.config/taskfiles/git/Taskfile.yml
--- a/.config/taskfiles/git/Taskfile.yml
+++ b/.config/taskfiles/git/Taskfile.yml
@@ -4,7 +4,7 @@ version: '3'
 vars:
   EMOJI_END:
     sh: |
-      if [ -f '.variables.json' ]; then
+      if [ -f '.variables.json' ] && type jq &> /dev/null; then
         BP_END="$(jq -r '.emoji_end' .variables.json)"
         if [ "$BP_END" != 'null' ]; then
           echo "$BP_END"
@@ -18,7 +18,7 @@ vars:
       fi
   EMOJI_START:
     sh: |
-      if [ -f '.variables.json' ]; then
+      if [ -f '.variables.json' ] && type jq &> /dev/null; then
         BP_START="$(jq -r '.emoji_start' .variables.json)"
         if [ "$BP_START" != 'null' ]; then
           echo "$BP_START"
@@ -40,15 +40,18 @@ env:
 
 tasks:
   commit:automated:
+    deps:
+      - remotes
     log:
       start: Running automated commit
     cmds:
-      - cmd: |
-          if [[ "$FULLY_AUTOMATED_TASKS" == 'true' ]]; then
-            git add --all
-            HUSKY=0 git commit -m "☁️ Automation" -n
-          fi
+      - task --list > /dev/null || (echo "ERROR > Invalid Taskfile(s)!" && exit 1)
+      - git add --all
+      - cmd: >
+          HUSKY=0 git commit -m "☁️ chore(automation): Automated update" -n
         ignore_error: true
+    status:
+      - '[ "$FULLY_AUTOMATED_TASKS" != "true" ] || [ "$SEMANTIC_RELEASE" == "true" ]'
 
   convert:folder:submodule:
     deps:
@@ -67,18 +70,15 @@ tasks:
       - git init
       - git remote add origin "{{.GITLAB_REPO}}"
       - git add --all
-      - git commit --quiet -m "refactor(convert-dir-to-submodule) Adding folder/project to its own git repository."
+      - git commit --quiet -m "🧐 refactor(submodule): Adding folder/project to its own git repository."
       - git push --quiet -u --no-progress origin master
-      - |
-        cd ..
-        rm -rf {{.BASENAME}}
-        git add {{.BASENAME}}
-        git commit --quiet -m "refactor(convert-dir-to-submodule) Removing folder which will now be a submodule."
-        git submodule add -b master "{{.GITLAB_REPO}}" {{.BASENAME}}
-        git add {{.BASENAME}}
-        git commit --quiet -m "refactor(convert-dir-to-submodule) Adding new submodule which was previously a directory."
-        git push --quiet -u --no-progress origin HEAD
-      - .config/log success ''
+      - cd .. && rm -rf {{.BASENAME}}
+      - cd .. && git add {{.BASENAME}}
+      - cd .. && git commit --quiet -m "🧐 refactor(submodule): Removing folder which will now be a submodule."
+      - cd .. && git submodule add -b master "{{.GITLAB_REPO}}" {{.BASENAME}}
+      - cd .. && git add {{.BASENAME}}
+      - cd .. && git commit --quiet -m "🧐 refactor(submodule): Adding new submodule which was previously a directory."
+      - cd .. && git push --quiet -u --no-progress origin HEAD
     preconditions:
       - sh: '[[ ! $(git rev-parse --git-dir) =~ ".git/modules" ]]'
         msg: Cannot convert the directory to a submodule - the directory already appears to be a submodule.
@@ -104,16 +104,35 @@ tasks:
         RELATIVE_DIR="$(echo $ROLE_DIR | sed 's@'"$PWD"'/@@')"
         HUSKY=0 git subrepo clone {{.BASENAME}} "$RELATIVE_DIR" -b master
 
+  filter:
+    log:
+      error: Error filtering git history
+      start: Filtering unnecessary items from git history
+      success: Successfully filtered unnecessary items from git history
+    cmds:
+      - git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch -r **/node_modules/' --prune-empty -- --all
+
   push:all:
+    deps:
+      - :ci:commit:config
     log:
       error: Encountered error while running `git push all master --force || git push origin master`
       start: Running `git push all master --force || git push origin master`
       success: Successfully ran `git push all master --force || git push origin master`
     cmds:
       - |
-        if [[ "$FULLY_AUTOMATED_TASKS" == 'true' ]]; then
-          git push all master --force || git push origin master
+        if ! git push all master --force; then
+          git pull -X theirs origin master
+          git add --all
+          HUSKY=0 git commit -m "☁️ chore(automation): Automated update to all remotes" -n
+          if ! git push all master --force; then
+            task git:gitlab:protected:off -- "master"
+            git push all master --force
+            task git:gitlab:protected:on -- "master"
+          fi
         fi
+    status:
+      - '[ -n "$CI" ] || [ "$SEMANTIC_RELEASE" == "true" ] || [ "$FULLY_AUTOMATED_TASKS" != "true" ]'
 
   remotes:
     deps:
@@ -177,9 +196,9 @@ tasks:
           .config/log success 'Added git remote named `all`'
         fi
     status:
-      - '[[ "$(git config remote.all.url)" == "${GITLAB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
-      - '[[ "$(git config remote.github.url)" == "${GITHUB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
-      - '[[ "$(git config remote.gitlab.url)" == "${GITLAB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
+      - '[[ "$(git config remote.all.url)" == "${GITLAB_REPO}.git" ]] || [ -n "$CI" ]'
+      - '[[ "$(git config remote.github.url)" == "${GITHUB_REPO}.git" ]] || [ -n "$CI" ]'
+      - '[[ "$(git config remote.gitlab.url)" == "${GITLAB_REPO}.git" ]] || [ -n "$CI" ]'
 
   remove:history:cli:
     deps:
@@ -251,18 +270,16 @@ tasks:
         fi
 
   update:
+    run: once
     cmds:
       - task: :git:gitlab:create
       - task: :git:github:create
       - task: update:continue
+    status:
+      - '[ -n "$CI" ] || ([ -z "$GITLAB_TOKEN" ] && [ -z "$GITHUB_TOKEN" ])'
 
   update:continue:
     deps:
       - :git:gitlab:update
       - :git:github:update
-    cmds:
-      - |
-        if ! git push -u origin master; then
-          git pull origin master --allow-unrelated-histories
-          git push origin -u origin master
-        fi
+    run: once
diff --git a/.config/taskfiles/lint/Taskfile.yml b/.config/taskfiles/lint/Taskfile.yml
--- a/.config/taskfiles/lint/Taskfile.yml
+++ b/.config/taskfiles/lint/Taskfile.yml
@@ -22,7 +22,7 @@ tasks:
   ansible:
     deps:
       - :symlink:{{.REPOSITORY_SUBTYPE}}
-      - :install:python:requirements
+      - :install:pipx:ansible-lint
     desc: Lint Ansible projects using Ansible Lint
     hide: '{{ne .REPOSITORY_TYPE "ansible"}}'
     summary: |
@@ -42,21 +42,22 @@ tasks:
       start: Linting project with Ansible Lint
       success: Validated project with Ansible Lint
     cmds:
-      - '{{.PYTHON_HANDLE}}ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}'
+      - ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
 
   any:
     deps:
-      - :install:python:requirements
+      - :install:pipx:blocklint
+      - :install:pipx:pre-commit-hooks
     desc: Generic linting of files for things like destroyed-symlinks, merge conflicts, etc.
     log:
       error: Errors were reported by the global linters for `{{.CLI_ARGS}}`
       start: Linting `{{.CLI_ARGS}}` with global linters
     cmds:
-      - '{{.PYTHON_HANDLE}}blocklint --wordlist blacklist,slave,whitelist {{.CLI_ARGS}}'
-      - '{{.PYTHON_HANDLE}}check-merge-conflict {{.CLI_ARGS}}'
-      - '{{.PYTHON_HANDLE}}check-added-large-files {{.CLI_ARGS}}'
-      - '{{.PYTHON_HANDLE}}check-symlinks {{.CLI_ARGS}}'
-      - '{{.PYTHON_HANDLE}}destroyed-symlinks {{.CLI_ARGS}}'
+      - blocklint --wordlist blacklist,slave,whitelist {{.CLI_ARGS}}
+      - check-merge-conflict {{.CLI_ARGS}}
+      - check-added-large-files {{.CLI_ARGS}}
+      - check-symlinks {{.CLI_ARGS}}
+      - destroyed-symlinks {{.CLI_ARGS}}
 
   codeclimate:
     deps:
@@ -90,7 +91,17 @@ tasks:
       start: Running `codeclimate`
       success: Successfully validated the project by running `codeclimate`
     cmds:
-      - CODECLIMATE_DEBUG=1 codeclimate analyze --dev{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
+      - |
+        if [ -z "$CODECLIMATE_INTEGRATION_TEST" ]; then
+          CODECLIMATE_DEBUG=1 codeclimate analyze --dev{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
+        else
+          while read PATHH; do
+            cd "$(dirname $PATHH)" && break
+          done < <(find test -maxdepth 2 -type f -name .codeclimate.yml)
+          task lint:codeclimate:taskfiles:add
+          CODECLIMATE_DEBUG=1 codeclimate analyze --dev
+          task lint:codeclimate:taskfiles:remove
+        fi
 
   commit:
     deps:
@@ -114,7 +125,7 @@ tasks:
           TMP="$(mktemp)"
           COMMIT_MSG_NOEMOJI="$(sed 's/^..//' < '{{.CLI_ARGS}}' | xargs)"
           .config/log info 'Linting commit message (with emoji stripped)'
-          echo "$COMMIT_MSG_NOEMOJI" | {{.NPX_PACKAGE}} commitlint || (mv '{{.CLI_ARGS}}.bak' '{{.CLI_ARGS}}' && exit 1)
+          echo "$COMMIT_MSG_NOEMOJI" | {{.NPX_HANDLE}}commitlint || (mv '{{.CLI_ARGS}}.bak' '{{.CLI_ARGS}}' && exit 1)
         elif [ '{{.CLI_ARGS}}' == '.git/MERGE_MSG' ]; then
           .config/log info 'Bypassing commitlint since the message is a merge message'
         fi
@@ -167,11 +178,11 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
-          docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim {{.CLI_ARGS | replace .PWD ""}}
+          docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim -c .config/hadolint.yml {{.CLI_ARGS | replace .PWD ""}}
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name Dockerfile -o \
             -name Dockerfile.j2 \) -print0 | xargs -0 -r -n1 docker run -v "$PWD:/work" -w /work \
-            megabytelabs/hadolint:slim
+            megabytelabs/hadolint:slim -c .config/hadolint.yml
         {{end}}
 
   dockerfile:
@@ -274,13 +285,15 @@ tasks:
         done < "$ESLINT_TMP"
 
   go:
-    desc: Lint Go with all available Go linters
+    deps:
+      - :install:software:go
+      - :install:software:golangci-lint
+    desc: Lint Go with `golangci-lint`
     summary: |
       # Lint Go Files
 
-      This task will lint Go files with the following linters:
-
-      * [go]()
+      This task will lint Go files with `golangci-lint`. The configuration is
+      stored in `.config/golangci.yml` and uses a handful of linters.
 
       If you would like to skip linting the whole project and instead lint an
       individual file, then you can do so by passing the file path as a CLI
@@ -288,39 +301,12 @@ tasks:
 
       **Example linting individual file:**
       `task lint:go -- path/filename.go`
+    log:
+      error: Detected errors with `golangci-lint`
+      start: Linting with `golangci-lint`
+      success: Successfully completed linting with `golangci-lint`
     cmds:
-      - task: go:vet
-
-  go:vet:
-    deps:
-      - :install:software:go
-    summary: |
-      # Inspect with Go Vet
-
-      This task inspects the source code with `go vet`.
-
-      If you need to add flags to the command, you can specify them in
-      `blueprint.goVetFlags`. `goVetFlags` can also be set in upstream variable
-      sources but this lint command does not force the generation of the
-      `.variables.json` file. If it cannot read `goVetFlags` in the `.variables.json` file
-      (perhaps because it was not generated yet), it will read `.blueprint.goVetFlags`
-      from `package.json`.
-
-      If you would like to run `go vet` on a specific path then you can pass the path
-      in as a CLI argument.
-
-      **Example of running `go vet` on a specific path:**
-      `task lint:go:vet -- path/to/file.go`
-    vars:
-      GO_VET_FLAGS:
-        sh: |
-          if [ -f .variables.json ]; then
-            echo " $(jq -r '.goVetFlags' .variables.json)"
-          else
-            echo " $(jq -r '.blueprint.goVetFlags' package.json | sed 's/null//')"
-          fi
-    cmds:
-      - go vet{{.GO_VET_FLAGS}}{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}
+      - golangci-lint run -c .config/golangci.yml{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
 
   js:
     deps:
@@ -337,15 +323,20 @@ tasks:
 
   lint-staged:
     deps:
-      - :install:modules:global
       - :install:modules:local
-      - :install:python:requirements
+      - :install:npm:lint-staged
     log:
       error: Errors were encountered when validating the staged files
       start: Linting staged files
       success: The staged files appear to be good!
     cmds:
-      - '{{.NPX_HANDLE}}lint-staged'
+      - |
+        {{.NPX_HANDLE}}lint-staged || LINT_EXIT_CODE="$?"
+        if [ -n "$LINT_EXIT_CODE" ]; then
+          .config/log error 'Linting failed!'
+          .config/log info 'If necessary, you can bypass this pre-commit hook by running `git commit --no-verify`. Please try to fix the errors first.'
+          exit 1
+        fi
 
   packer:
     deps:
@@ -431,7 +422,7 @@ tasks:
 
   python:
     deps:
-      - :install:python:requirements
+      - :install:pipx:flake8
     label: lint:python
     desc: Lint Python files using Flake8
     hide: '{{ne .REPOSITORY_TYPE "python"}}'
@@ -464,9 +455,9 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
-          {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} {{.CLI_ARGS}}
+          flake8 --config {{.FLAKE8_CONFIG}} {{.CLI_ARGS}}
         {{else}}
-          {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} .
+          flake8 --config {{.FLAKE8_CONFIG}} .
         {{end}}
 
   shell:
@@ -588,7 +579,7 @@ tasks:
 
   toml:
     deps:
-      - :install:python:requirements
+      - :install:pipx:pre-commit-hooks
     summary: |
       # Lint TOML files
 
@@ -605,7 +596,7 @@ tasks:
       start: Ensuring {{if .CLI_ARGS}}`{{.CLI_ARGS}}` is valid TOML{{else}}the project'\''s TOML files are valid{{end}}
       success: The TOML appears to be valid!
     cmds:
-      - '{{.PYTHON_HANDLE}}check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   vagrant:
     deps:
@@ -630,7 +621,7 @@ tasks:
 
   xml:
     deps:
-      - :install:python:requirements
+      - :install:pipx:pre-commit-hooks
     summary: |
       # Lint XML files
 
@@ -647,11 +638,11 @@ tasks:
       start: Ensuring {{if .CLI_ARGS}}{{.CLI_ARGS}} is valid XML{{else}}the project contains only valid XML{{end}}
       success: The XML appears to be valid
     cmds:
-      - '{{.PYTHON_HANDLE}}check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   yaml:
     deps:
-      - :install:python:requirements
+      - :install:pipx:yamllint
     desc: Lint `.yml` files using YAML Lint
     summary: |
       # Lint YML files using YAML Lint
@@ -678,4 +669,4 @@ tasks:
       start: Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with `yamllint`
       success: No issues were detected by `yamllint`
     cmds:
-      - '{{.PYTHON_HANDLE}}yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
